[WIP] Feat/add pull client method
uor-framework/client pull request #25
Opened 2022-06-14 14:47 UTC by jpower432

Adds the ability to pull artifacts with a pull command.

- [X] Unit tests added
- [X] E2E tests modified
- [ ] Docs updated

2022-06-17 14:05 UTC, sabre1041 requested changes
This looks really good and validated the capabilities 

A few small requests for modifications

2022-06-17 14:13 UTC, jpower432 commented on README.md
> +client build --dsconfig dataset-config.yaml content-dir --output my-workspace
I will fix that. Thanks!

2022-06-17 14:26 UTC, sabre1041 commented on README.md
> +### Pull artifact to a location
Should this be renamed `artifact` -> `collection`

2022-06-21 05:02 UTC, sabre1041 approved these changes
LGTM

2022-06-21 05:02 UTC, merged