build multi-arch binaries and multi-arch container
uor-framework/client pull request #39
Opened 2022-07-10 00:13 UTC by usrbinkat

## Does:
Build multi-arch binaries and containers.

## Does not:
Does not automate the publishing of all binaries or pushing container.

## How To:
```sh
make build-all-arch
make container
make container-push
```
or
```sh
make all
make container-push
```

## Other:
closes #38

2022-07-10 17:08 UTC, sabre1041 requested changes
Like where this is headed. A few areas to address

2022-07-10 17:08 UTC, sabre1041 commented on Makefile
> +	buildah manifest create ghcr.io/uor-framework/client:$(GIT_TAG)
Support should be available to use either Docker or Red Hat Container Tools (Podman/Buildah etc). Logic should be added to determine which are available on host machine.

Required tools should also be documented

2022-07-10 22:19 UTC, usrbinkat commented on Makefile
>  	mkdir -p ${GO_BUILD_BINDIR}
I considered this, I am happy to consolidate `build-all-arch` and `build` targets if that is the correct approach.

2022-07-11 18:14 UTC, sabre1041 approved these changes
LGTM

2022-07-11 18:39 UTC, merged

2022-07-17 18:25 UTC, vsoch commented
Any reason to not automate pushing the containers to ghcr.io?

2022-07-17 20:05 UTC, sabre1041 commented
@vsoch It's on the week. See this [PR](https://github.com/uor-framework/client/pull/42)

2022-07-17 21:16 UTC, vsoch commented
Ah perfecto! I'll follow instructions from there, or if the PR will be reviewed/merged soon I can test the resulting containers. Thank you @sabre1041 !

2022-07-17 21:17 UTC, sabre1041 commented
@vsoch PR will be reviewed today/tomorrow. will let you know when assets are ready for a review!